### ISSUE TITLE
Applications Konsole, gwenview and kate missing

### ISSUE THREAD

**Issue by Sannythebest** [Antergos/kde-setup#6]
Hello, I noticed that the change of the name of the app in the repo of Arch no longer install these applications, which then needs to be installed later
I think prevents this problem will occur even when the app will go to other KF5

**Comment by Sannythebest** [comment]
Sorry, I have noticed that they have already reported the problem
I have to close?

**Comment by MichaelTunnell** [comment]
this is pretty much what I was talking about in this issue, https://github.com/Antergos/kde-setup/issues/4
